similarity_threshold: 0.7
keyword_match_threshold: 0.3
fuzzy_match_threshold: 70
levenshtein_similarity_threshold: 0.7

weights:
  similarity: 1.0
  keyword_match: 1.0
  fuzzy_match: 1.0
  levenshtein_similarity: 1.0
